apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: postgresql
      repository:
        url: oci://registry-1.docker.io/bitnamicharts
      version: 18.11.4
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-postgresql-18.11.4-efc48e41c76c4505/data
kind: Config
minimumRequiredVersion: ""
