apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: redis
      repository:
        url: oci://registry-1.docker.io/bitnamicharts
      version: 27.0.0
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-redis-27.0.0-e71122b68a8ed6c2/data
kind: Config
minimumRequiredVersion: ""
