apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: redis
      repository:
        url: oci://registry-1.docker.io/bitnamicharts
      version: 28.2.2
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-redis-28.2.2-2a2869a6f876df93/data
kind: Config
minimumRequiredVersion: ""
