apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: traefik
      repository:
        url: https://traefik.github.io/charts
      version: 41.2.0
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-traefik-41.2.0-7b3ada7a3a9b2293/data
kind: Config
minimumRequiredVersion: ""
