apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.49.0
overrides:
- image: ecr-public.aws.com/docker/library/redis:8.2.3-alpine
  newImage: ecr-public.aws.com/docker/library/redis@sha256:08ad0b1d280850169a790dba1393ff7a90aef951fc19632cf4d3ce4f78e679ba
  preresolved: true
- image: ghcr.io/dexidp/dex:v2.45.1
  newImage: oci.zebradil.dev/ghcr.io-cache/dexidp/dex@sha256:8499afd690c437f52301efd2b05b2455da5bd2dfc20332cd697dc9937f808462
  preresolved: true
- image: ghcr.io/oliver006/redis_exporter:v1.87.0
  newImage: oci.zebradil.dev/ghcr.io-cache/oliver006/redis_exporter@sha256:9ca6f929a8abc518d78158757922444f1cf807661a2238f44b28c3cd08a1b652
  preresolved: true
- image: quay.io/argoproj/argocd:v3.4.5
  newImage: oci.zebradil.dev/quay.io-cache/argoproj/argocd@sha256:224e454cfd8c1818fec3ed17b72b2034c9a3915fa819e1dcccafc753776d446a
  preresolved: true
- image: registry.access.redhat.com/ubi8
  newImage: oci.zebradil.dev/registry.access.redhat.com-cache/ubi8@sha256:bd18177f9f1682ae91fb335aa1939f6eff5c8c2426381824444d3eb4bb583ad3
  preresolved: true
