apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.49.0
overrides:
- image: ecr-public.aws.com/docker/library/redis:8.6.4-alpine
  newImage: ecr-public.aws.com/docker/library/redis@sha256:2cc044fc5a07c9b701f8f1255a309ae9ad7856e694ac03513bf3648c01e40763
  preresolved: true
- image: ghcr.io/dexidp/dex:v2.45.1
  newImage: oci.zebradil.dev/ghcr.io-cache/dexidp/dex@sha256:8499afd690c437f52301efd2b05b2455da5bd2dfc20332cd697dc9937f808462
  preresolved: true
- image: ghcr.io/oliver006/redis_exporter:v1.89.0
  newImage: oci.zebradil.dev/ghcr.io-cache/oliver006/redis_exporter@sha256:fed773ffd2bb2eac706e0ed9cc2fff41651193ee4977e2a4f6919658ad2313f4
  preresolved: true
- image: quay.io/argoproj/argocd:v3.5.1
  newImage: oci.zebradil.dev/quay.io-cache/argoproj/argocd@sha256:0deb1a1c917629b960ead995ae3b6069450a866992676599658687ef9a641ee8
  preresolved: true
- image: registry.access.redhat.com/ubi8
  newImage: oci.zebradil.dev/registry.access.redhat.com-cache/ubi8@sha256:f21f2e9672d3b4e5f49b6ed88fb318a8852696f873d685b9b53d0387d1c74907
  preresolved: true
