apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.47.2
overrides:
- image: ecr-public.aws.com/docker/library/redis:8.2.3-alpine
  newImage: ecr-public.aws.com/docker/library/redis@sha256:08ad0b1d280850169a790dba1393ff7a90aef951fc19632cf4d3ce4f78e679ba
  preresolved: true
- image: ghcr.io/dexidp/dex:v2.45.1
  newImage: oci.zebradil.dev/ghcr.io-cache/dexidp/dex@sha256:8499afd690c437f52301efd2b05b2455da5bd2dfc20332cd697dc9937f808462
  preresolved: true
- image: quay.io/argoproj/argocd:v3.3.7
  newImage: oci.zebradil.dev/quay.io-cache/argoproj/argocd@sha256:31f494ef5ad17b8dfd4e03fbae79c57cfadede325ed16a1794ee9ce20ca5d759
  preresolved: true
- image: registry.access.redhat.com/ubi8
  newImage: oci.zebradil.dev/registry.access.redhat.com-cache/ubi8@sha256:6dc1b728df2fc2c5b3e90f6c16fdd342dab32e75f80785dd1052fb40898cc726
  preresolved: true
