apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: argo-cd
      repository:
        url: https://argoproj.github.io/argo-helm
      version: 10.9.2
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-argo-cd-10.9.2-f7b6c0b652c34d4e/data
kind: Config
minimumRequiredVersion: ""
