apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.47.2
overrides:
- image: linuxserver/librespeed:5.5.1
  newImage: index.docker.io/linuxserver/librespeed@sha256:110df57cd248672c98fd3e6758314ad36755c28620e231a04bddc7c835c19a09
  preresolved: true
