apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: postgresql
      repository:
        url: oci://registry-1.docker.io/bitnamicharts
      version: 18.5.22
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-postgresql-18.5.22-55cecef509f2610a/data
kind: Config
minimumRequiredVersion: ""
