apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: traefik
      repository:
        url: https://traefik.github.io/charts
      version: 41.0.0
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-traefik-41.0.0-e806bc4b9d6a55d9/data
kind: Config
minimumRequiredVersion: ""
