apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.49.0
overrides:
- image: busybox:1.36.1
  newImage: index.docker.io/library/busybox@sha256:73aaf090f3d85aa34ee199857f03fa3a95c8ede2ffd4cc2cdb5b94e566b11662
  preresolved: true
- image: filebrowser/filebrowser:v2.63.18
  newImage: index.docker.io/filebrowser/filebrowser@sha256:c4c627f687668c5a02ab410d8473712c77be7f1f0ea4f8d624d2a1392c495e76
  preresolved: true
- image: ghcr.io/hotio/qbittorrent:release-4.6.4
  newImage: oci.zebradil.dev/ghcr.io-cache/hotio/qbittorrent@sha256:39829b3e092a91fb15f6696d5a8b762a2da6436ff59e529e13305e6bfb52f829
  preresolved: true
- image: ghcr.io/linuxserver/wireguard:v1.0.20210914-ls31
  newImage: oci.zebradil.dev/ghcr.io-cache/linuxserver/wireguard@sha256:c417568c79a051a8a73ffc2ad28ef58f58ba76bdb4c420389819c001aa55a03e
  preresolved: true
- image: jellyfin/jellyfin:10.11.11
  newImage: index.docker.io/jellyfin/jellyfin@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db
  preresolved: true
