#@ load("@ytt:data", "data")
#@ load("util.star", res="resources")

#@ pg = data.values.application.postgresql
---
auth:
  database: #@ pg.database
  password: #@ pg.password
  postgresPassword: #@ pg.password
  username: #@ pg.username
image:
  repository: bitnamilegacy/postgresql
  tag: 14.18.0-debian-12-r0
primary:
  resources: #@ res("20m", "64Mi", "256Mi")
  persistence:
    size: 1Gi
