#@ load("@ytt:data", "data")
#@ load("util.star", res="resources")
---
architecture: standalone
auth:
  enabled: false
image:
  repository: bitnamilegacy/redis
  tag: 8.2.1-debian-12-r0
master:
  persistence:
    enabled: false
  resources: #@ res("30m", "16Mi", "128Mi")
