apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: redis
            repository:
                url: oci://registry-1.docker.io/bitnamicharts
            version: 20.7.1
          lazy: true
          path: .
      path: .myks/vendir-cache/helm-redis-20.7.1-ce5a2c1daa6f795e/data
      permissions: null
kind: Config
