apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.49.0
overrides:
- image: ghcr.io/zebradil/kasha-box:edge
  newImage: oci.zebradil.dev/ghcr.io-cache/zebradil/kasha-box@sha256:1c0e0c3dbf02c586d487b70d005b98b2ced9bcd4cbe92076e72cde06a28c089e
  preresolved: true
