apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.49.0
overrides:
- image: ghcr.io/zebradil/kasha-box:edge
  newImage: oci.zebradil.dev/ghcr.io-cache/zebradil/kasha-box@sha256:f2c01828f5031f0ab394715d525c37cbbf93abf0885b79eb0cc919e42df61d2a
  preresolved: true
