apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.49.1
overrides:
- image: ghcr.io/zebradil/kasha-box:edge
  newImage: oci.zebradil.dev/ghcr.io-cache/zebradil/kasha-box@sha256:3f3bca3b687f7677e8a628cf5241a8991ac934960317d4787a6a6a0b58094b48
  preresolved: true
