apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: argo-cd
      repository:
        url: https://argoproj.github.io/argo-helm
      version: 10.9.5
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-argo-cd-10.9.5-36e75ce6e1b29957/data
kind: Config
minimumRequiredVersion: ""
