apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.48.0
overrides:
- image: mccutchen/go-httpbin:2.23.0
  newImage: index.docker.io/mccutchen/go-httpbin@sha256:b5d2ef3378e61138998cb4e60edf117000594f33b9be504825921190a7109e69
  preresolved: true
