apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: postgresql
      repository:
        url: oci://registry-1.docker.io/bitnamicharts
      version: 18.7.5
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-postgresql-18.7.5-56cdbd73f4943be7/data
kind: Config
minimumRequiredVersion: ""
