apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: authelia
      repository:
        url: https://charts.authelia.com
      version: 0.11.22
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-authelia-0.11.22-2def4c5d6bb6ff1/data
kind: Config
minimumRequiredVersion: ""
