#@ load("@ytt:data", "data")
#@ load("secrets.star", "sops")

#@ name = data.values.myks.context.app
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ name
stringData:
  AWS_ACCESS_KEY_ID: #@ sops("0", "aws-access-key-id")
  AWS_SECRET_ACCESS_KEY: #@ sops("0", "aws-secret-access-key")
