apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: redis
      repository:
        url: oci://registry-1.docker.io/bitnamicharts
      version: 25.2.0
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-redis-25.2.0-199a2e81c4289972/data
kind: Config
minimumRequiredVersion: ""
