apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: postgresql
      repository:
        url: oci://registry-1.docker.io/bitnamicharts
      version: 18.11.1
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-postgresql-18.11.1-8d9052804c9a60da/data
kind: Config
minimumRequiredVersion: ""
