#@ load("@ytt:data", "data")
#@ load("/secrets.star", "sops")

#@ dv = data.values
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ dv.application._.secretName
  namespace: #@ dv.helm.namespace
stringData: #@ { "github_app_" + k: sops("0", k) for k in ["id", "installation_id", "private_key"] }
