#@ load("@ytt:data", "data")
#@ load("/secrets.star", "sops")

#@ dv = data.values
#@ a = dv.application

#@ for/end ns in [a.arcNamespace, a.runnersNamespace]:
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ a._.secretName
  namespace: #@ ns
stringData: #@ { "github_app_" + k: sops("0", k) for k in ["id", "installation_id", "private_key"] }
