apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: redis
      repository:
        url: oci://registry-1.docker.io/bitnamicharts
      version: 27.0.9
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-redis-27.0.9-72188a10f3993299/data
kind: Config
minimumRequiredVersion: ""
