apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: argo-cd
      repository:
        url: https://argoproj.github.io/argo-helm
      version: 10.9.1
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-argo-cd-10.9.1-827004c50b17bbe3/data
kind: Config
minimumRequiredVersion: ""
