apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.48.0
overrides:
- image: oci.zebradil.dev/zebradil/know-mcp:latest
  newImage: oci.zebradil.dev/zebradil/know-mcp@sha256:f8dc097cf06b6669f51b5b7bf0facebad985d83883e152cd9774964fe196ca10
  preresolved: true
