apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.48.0
overrides:
- image: oci.zebradil.dev/zebradil/know-mcp:latest
  newImage: oci.zebradil.dev/zebradil/know-mcp@sha256:8e5405fc076c6671b243f6899c80da06a2462154521b95ae2884bcee000824d5
  preresolved: true
