apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: authelia
      repository:
        url: https://charts.authelia.com
      version: 0.11.20
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-authelia-0.11.20-b86bad58be2e5df3/data
kind: Config
minimumRequiredVersion: ""
