#!/usr/bin/env bash

# Refresh Argo CD application

set -euo pipefail

: "${ARGOCD_SERVER:?Environment variable ARGOCD_SERVER must be set}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"

l:ensure_login
l:argocd app get "app-${MYKS_ENV}-${MYKS_APP}" --refresh >/dev/null
