apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: harbor
      repository:
        url: https://helm.goharbor.io
      version: 1.19.2
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-harbor-1.19.2-3f5b5d0dea3736be/data
kind: Config
minimumRequiredVersion: ""
