apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: redis
      repository:
        url: oci://registry-1.docker.io/bitnamicharts
      version: 28.0.10
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-redis-28.0.10-fc5f3f9b0cc35df8/data
kind: Config
minimumRequiredVersion: ""
