apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.49.1
overrides:
- image: ghcr.io/zebradil/airgradient-exporter:1.2.0
  newImage: oci.zebradil.dev/ghcr.io-cache/zebradil/airgradient-exporter@sha256:e1c4fe838bc42b32f6883bc068c69d13ae08c02125d571dfcd2ecb2ededdcce7
  preresolved: true
