apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: ytt/dashboard
  contents:
  - path: .
    lazy: true
    git:
      url: https://github.com/zebradil/airgradient-exporter
      ref: 1.2.8
    includePaths:
    - dashboard/dashboard.json
    newRootPath: dashboard
