apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.47.1
overrides:
- image: docker.io/traefik:v3.6.11
  newImage: oci.zebradil.dev/index.docker.io-cache/library/traefik@sha256:acfc80650104f0194a15f73dc1648f517561bc1645391a15705332a064cfc33c
  preresolved: true
- image: registry.access.redhat.com/ubi8/ubi:8.9
  newImage: oci.zebradil.dev/registry.access.redhat.com-cache/ubi8/ubi@sha256:83068ea81dd02717b8e39b55cdeb2c1b2c9a3db260f01381b991755d44b15073
  preresolved: true
searchRules:
- keyMatcher:
    path:
    - data
    - images.txt
  updateStrategy:
    yaml:
      searchRules:
      - keyMatcher:
          name: image
