apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: postgresql
      repository:
        url: oci://registry-1.docker.io/bitnamicharts
      version: 18.8.0
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-postgresql-18.8.0-63d3516b2f7993d/data
kind: Config
minimumRequiredVersion: ""
