apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.47.2
overrides:
- image: quay.io/jetstack/cert-manager-cainjector:v1.20.2
  newImage: oci.zebradil.dev/quay.io-cache/jetstack/cert-manager-cainjector@sha256:6f5a644135887b2aa7d5cc145072fa56421560e3586ff1f184358022d490f4e1
  preresolved: true
- image: quay.io/jetstack/cert-manager-controller:v1.20.2
  newImage: oci.zebradil.dev/quay.io-cache/jetstack/cert-manager-controller@sha256:fe0623d7d04a382c888f03343a3a2da716e0d96ad3d5d790c0ebcbcb2a4329a5
  preresolved: true
- image: quay.io/jetstack/cert-manager-startupapicheck:v1.20.2
  newImage: oci.zebradil.dev/quay.io-cache/jetstack/cert-manager-startupapicheck@sha256:4e2a69b4a0cc9627905bbeecf720f95d5153ca39cacdab923d2748e73556792b
  preresolved: true
- image: quay.io/jetstack/cert-manager-webhook:v1.20.2
  newImage: oci.zebradil.dev/quay.io-cache/jetstack/cert-manager-webhook@sha256:baf651128b9f05c426cbd5e60e2036bf382c99ca270f49d0757d6f7d2452f4e5
  preresolved: true
