#@data/values

#@ arc_namespace = "arc-system"
#@ runners_namespace = "arc-runners"
---
application:
  arcNamespace: #@ arc_namespace
  runnersNamespace: #@ runners_namespace
  githubConfigUrl: https://github.com/zebradilo
argocd:
  app:
    syncPolicy:
      syncOptions:
        #! Since this app is deployed to multiple namespaces, they're managed explicitly
        CreateNamespace: null
helm:
  charts:
    - name: arc
      namespace: #@ arc_namespace
    - name: scale-set
      namespace: #@ runners_namespace
render:
  includeNamespace: true
