apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: postgresql
      repository:
        url: oci://registry-1.docker.io/bitnamicharts
      version: 18.8.6
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-postgresql-18.8.6-daf371ff72da30ff/data
kind: Config
minimumRequiredVersion: ""
