---
fullnameOverride: vmks
victoria-metrics-operator:
  admissionWebhooks:
    certManager:
      enabled: true

vmagent:
  spec:
    extraArgs:
      promscrape.dropOriginalLabels: 'false'
  additionalRemoteWrites:
    - url: 'http://vminsert-vmks-long.vmks.svc.cluster.local.:8480/insert/0/prometheus/api/v1/write'
      inlineUrlRelabelConfig:
        - source_labels: [__name__]
          regex: 'airgradient_.*'
          action: keep

vmsingle:
  enabled: false

vmcluster:
  enabled: true
  spec:
    replicationFactor: 1
    retentionPeriod: 30d
    vmstorage:
      replicaCount: 1
    vmselect:
      enabled: false
    vminsert:
      replicaCount: 1

external:
  vm:
    read:
      url: 'http://vmselect-vmks-long.vmks.svc.cluster.local.:8481/select/0/prometheus'

kubeControllerManager:
  service:
    enabled: false

kubeScheduler:
  service:
    enabled: false
