---
fullnameOverride: vmks
victoria-metrics-operator:
  admissionWebhooks:
    certManager:
      enabled: true

vmagent:
  spec:
    extraArgs:
      promscrape.dropOriginalLabels: 'false'

vmsingle:
  enabled: false

vmcluster:
  enabled: true
  spec:
    replicationFactor: 1
    retentionPeriod: 30d
    vmstorage:
      replicaCount: 1
    vmselect:
      replicaCount: 1
    vminsert:
      replicaCount: 1

kubeControllerManager:
  service:
    enabled: false

kubeScheduler:
  service:
    enabled: false
