#@ load("secrets.star", "sops")
#@ load("util.star", res="resources")
---
grafana:
  resources: #@ res("20m", "384Mi", "1Gi")
  persistence:
    enabled: true
    size: 2Gi
    accessModes:
      - ReadWriteMany
  adminPassword: #@ sops("0", "adminPassword")
  service:
    portName: http
  grafana.ini:
    analytics:
      check_for_updates: false
      feedback_links_enabled: false
      reporting_enabled: false
  sidecar:
    resources: #@ res("10m", "96Mi", "192Mi")
    dashboards:
      searchNamespace: ALL
      skipReload: true
  plugins:
    - victoriametrics-metrics-datasource
    - victoriametrics-logs-datasource
  ingress:
    hosts:
      - grafana.lan.zebradil.dev
  initChownData:
    enabled: true
    resources: #@ res("10m", "16Mi", "64Mi")
