#! This file contains overlays that duplicate a VMCluster resource and changes properties of the copy.
#! YTT doesn't support duplication of documents out of the box, but in case of Kubernetes resources we can turn a single
#! resource into a list of resources with multiple items using "kind: List".

#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:yaml", "yaml")

#@ def clone_yf(yamlfragment):
#@   return yaml.decode(yaml.encode(yamlfragment))
#@ end

#! clone_sts is meant to be used by the overlay/replace action on a YAML document
#! src – the original resource
#! clone_patch – an overlay to be applied to the resource clone
#@ def clone_sts(src, clone_patch):
#@ cloned = clone_yf(src)
apiVersion: v1
kind: List
items:
  -  #@ src
  -  #@ overlay.apply(cloned, clone_patch)
#@ end

#! The main overlay that matches the source resource.
#! The body of the overlay is applied to the clone of the resource.
#@overlay/match by=overlay.subset({"kind": "VMCluster"})
#@overlay/replace via=clone_sts
---
metadata:
  #@overlay/replace via=lambda l, r: l + r
  name: -long
spec:
  retentionPeriod: 5y
  #@overlay/match missing_ok=True
  vmselect:
    replicaCount: 1
    extraArgs:
      storageNode: 'vmstorage-vmks-0.vmstorage-vmks.vmks.svc.cluster.local.:8401,vmstorage-vmks-long-0.vmstorage-vmks-long.vmks.svc.cluster.local.:8401'
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 2Gi
