{
 "title": "Airgradient Native",
 "description": "Dashboard for the Airgradient One native prometheus metrics exporter. Compatible with the 3.0.6 firmware.",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "serialno",
    "query": "label_values(airgradient_config_info,serialno)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Status (serial $serialno)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "serialno"
  },
  {
   "title": "Temperature (°C)",
   "type": "stat",
   "description": "Ambient temperature near the sensor.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(serialno) (airgradient_atmp{serialno=~\"$serialno\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Relative Humidity (%)",
   "type": "stat",
   "description": "Ambient relative humidity near the sensor.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(serialno) (airgradient_rhum{serialno=~\"$serialno\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "CO2 Level (ppm)",
   "type": "stat",
   "description": "Carbon dioxide concentration in the air. PPM (parts per million) reflects volumetric gas concentration. Standard unit for tracking CO2 buildup from human activity.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(serialno) (airgradient_rco2{serialno=~\"$serialno\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "PM1 μg/m3",
   "type": "stat",
   "description": "Total weight of particles with a diameter of 1.0 micrometers or smaller, in μg / m3",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(serialno) (airgradient_pm01{serialno=~\"$serialno\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "PM2.5 μg/m3",
   "type": "stat",
   "description": "Total weight of particles with a diameter of 2.5 micrometers or smaller, in μg / m3",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(serialno) (airgradient_pm02{serialno=~\"$serialno\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "PM10 μg/m3",
   "type": "stat",
   "description": "Total weight of particles with a diameter of 10.0 micrometers or smaller, in μg / m3",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(serialno) (airgradient_pm10{serialno=~\"$serialno\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "PM0.3 particles/dL",
   "type": "stat",
   "description": "Total number of particles with a diameter of 0.3 micrometers or smaller per 100ml air",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(serialno) (airgradient_pm003_count{serialno=~\"$serialno\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "NOx Index",
   "type": "stat",
   "description": "Unitless index (1 - 500) based on deviation from 24h baseline. 1 = baseline, >1 = more oxidizing gases present.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(serialno) (airgradient_nox_index{serialno=~\"$serialno\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "TVOC Index",
   "type": "stat",
   "description": "Unitless index (1 - 500) based on deviation from 24h baseline. 100 = baseline, >100 = more VOCs present compared to the 24-hour baseline, <100 = fewer VOCs compared to the 24-hour baseline. Index is used because MOx sensors respond broadly to many VOCs, making exact ppb estimates unreliable. Better for detecting relative changes in air quality. The VOC Index adapts its gain based on environment: in clean air it becomes more sensitive to small changes, and in polluted air, it reduces sensitivity to avoid saturation, ensuring relative changes remain meaningful.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(serialno) (airgradient_tvoc_index{serialno=~\"$serialno\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Temperature & Humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Temperature (°C)",
   "type": "timeseries",
   "description": "Ambient temperature near the sensor.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum by(serialno) (airgradient_atmp{serialno=~\"$serialno\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Relative Humidity (%)",
   "type": "timeseries",
   "description": "Ambient relative humidity near the sensor.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(serialno) (airgradient_rhum{serialno=~\"$serialno\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "CO2 PPM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CO2 Level (ppm)",
   "type": "timeseries",
   "description": "Carbon dioxide concentration in the air. PPM (parts per million) reflects volumetric gas concentration. Standard unit for tracking CO2 buildup from human activity.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "sum by(serialno) (airgradient_rco2{serialno=~\"$serialno\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Particle Pollution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "PM0.3 particles/dL",
   "type": "timeseries",
   "description": "Total number of particles with a diameter of 0.3 micrometers or smaller per 100ml air",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "particles/100ml" } },
   "targets": [
    {
     "expr": "sum by(serialno) (airgradient_pm003_count{serialno=~\"$serialno\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "PM1 μg/m3",
   "type": "timeseries",
   "description": "Total weight of particles with a diameter of 1.0 micrometers or smaller, in μg / m3",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "sum by(serialno) (airgradient_pm01{serialno=~\"$serialno\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "PM2.5 μg/m3",
   "type": "timeseries",
   "description": "Total weight of particles with a diameter of 2.5 micrometers or smaller, in μg / m3",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "sum by(serialno) (airgradient_pm02{serialno=~\"$serialno\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "PM10 μg/m3",
   "type": "timeseries",
   "description": "Total weight of particles with a diameter of 10.0 micrometers or smaller, in μg / m3",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "sum by(serialno) (airgradient_pm10{serialno=~\"$serialno\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "TVOC / NOx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "TVOC Index",
   "type": "timeseries",
   "description": "Unitless index (1 - 500) based on deviation from 24h baseline. 100 = baseline, >100 = more VOCs present compared to the 24-hour baseline, <100 = fewer VOCs compared to the 24-hour baseline. Index is used because MOx sensors respond broadly to many VOCs, making exact ppb estimates unreliable. Better for detecting relative changes in air quality. The VOC Index adapts its gain based on environment: in clean air it becomes more sensitive to small changes, and in polluted air, it reduces sensitivity to avoid saturation, ensuring relative changes remain meaningful.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "TVOC" } },
   "targets": [
    {
     "expr": "sum by(serialno) (airgradient_tvoc_index{serialno=~\"$serialno\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "NOx Index",
   "type": "timeseries",
   "description": "Unitless index (1 - 500) based on deviation from 24h baseline. 1 = baseline, >1 = more oxidizing gases present.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "NOx" } },
   "targets": [
    {
     "expr": "sum by(serialno) (airgradient_nox_index{serialno=~\"$serialno\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  }
 ]
}