apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.49.0
overrides:
- image: ghcr.io/mendhak/http-https-echo:41
  newImage: oci.zebradil.dev/ghcr.io-cache/mendhak/http-https-echo@sha256:2046be25f4a2c0bdda662ebfb7c2b7b60fc95c31d97987be143645a8a2194a40
  preresolved: true
