#@data/values
---
prototype:
  sources:
    postgresql:
      helmChart:
        url: oci://registry-1.docker.io/bitnamicharts
        version: 18.7.5
    redis:
      helmChart:
        url: oci://registry-1.docker.io/bitnamicharts
        version: 27.0.10
