apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: argo-cd
      repository:
        url: https://argoproj.github.io/argo-helm
      version: 10.1.4
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-argo-cd-10.1.4-b8fde9eb52a096f4/data
kind: Config
minimumRequiredVersion: ""
