apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: postgresql
      repository:
        url: oci://registry-1.docker.io/bitnamicharts
      version: 18.12.2
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-postgresql-18.12.2-c5aa2924e33ab0a6/data
kind: Config
minimumRequiredVersion: ""
