#@data/values
---
prototype:
  sources:
    arc:
      helmChart:
        name: gha-runner-scale-set-controller
        url: oci://ghcr.io/actions/actions-runner-controller-charts
        version: 0.14.2
    scale-set:
      helmChart:
        name: gha-runner-scale-set
        url: oci://ghcr.io/actions/actions-runner-controller-charts
        version: 0.14.2
