apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: traefik
      repository:
        url: https://traefik.github.io/charts
      version: 41.6.1
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-traefik-41.6.1-da54bd11143f37d0/data
kind: Config
minimumRequiredVersion: ""
