apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: k8s-monitoring
            repository:
                url: https://grafana.github.io/helm-charts
            version: 1.6.24
          path: .
      path: .myks/vendir-cache/helm-k8s-monitoring-1.6.24-5a00299999e518ee/data
      permissions: null
kind: Config
