apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - git:
      ref: v4.39.26
      url: https://github.com/authelia/authelia
    includePaths:
    - examples/grafana-dashboards/simple.json
    lazy: true
    newRootPath: examples
    path: .
  path: .myks/vendir-cache/git-authelia-v4.39.26-47803778b62b3f1a/data
kind: Config
minimumRequiredVersion: ""
