apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.49.1
overrides:
- image: linuxserver/librespeed:6.2.1
  newImage: index.docker.io/linuxserver/librespeed@sha256:3d245bb0bc414d0ebe405dcd4f97c660e11b332cea033a73138ce4429064ba8a
  preresolved: true
