apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: redis
      repository:
        url: oci://registry-1.docker.io/bitnamicharts
      version: 27.0.15
    lazy: true
    path: .
  path: .myks/vendir-cache/helm-redis-27.0.15-a26299a11d1bf55c/data
kind: Config
minimumRequiredVersion: ""
