#@ load("@ytt:data", "data")
#@ load("secrets.star", "sops")
#@ load("pem.star", "pem_env")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.myks.context.app
stringData: #@ {pem_env(app): sops("0", pem_env(app)) for app in data.values.application.octosts.apps}
