apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: redis
            repository:
                url: oci://registry-1.docker.io/bitnamicharts
            version: 24.0.0
          lazy: true
          path: .
      path: .myks/vendir-cache/helm-redis-24.0.0-b2b1e30e9c805134/data
      permissions: null
kind: Config
