apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: ytt/dashboard
  contents:
  - path: .
    lazy: true
    git:
      url: https://github.com/zebradil/kasha
      ref: v0.7.0
    includePaths:
    - deploy/grafana/kasha.json
    newRootPath: deploy/grafana
