apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.48.0
overrides:
- image: caddy-image-ref
  newImage: oci.zebradil.dev/zebradil/homelab/maks-cams/caddy@sha256:9527c8b401482067a6608aad55628798905892e1f7d0356fb999e10d0d79d44d
  preresolved: true
