apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.47.3
overrides:
- image: caddy-image-ref
  newImage: oci.zebradil.dev/zebradil/homelab/maks-cams/caddy@sha256:3129450a9d033fe3a8b54afb5172102865634163260dd5aed577d1d5327b866e
  preresolved: true
