apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.49.1
overrides:
- image: caddy-image-ref
  newImage: oci.zebradil.dev/zebradil/homelab/maks-cams/caddy@sha256:8b9154c8ba086962fce089d85c0b06db9d5e788715fecc1ea79dbae0a3bdce33
  preresolved: true
