apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.49.1
overrides:
- image: caddy-image-ref
  newImage: oci.zebradil.dev/zebradil/homelab/maks-cams/caddy@sha256:b71573d0b0beef31dfe5c10f01abb3b13acbed1e54ac04a5020a78889f6e6742
  preresolved: true
