apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.47.3
overrides:
- image: louislam/uptime-kuma:2.3.0
  newImage: index.docker.io/louislam/uptime-kuma@sha256:a8e5e69ce185d5425fcbf2ab14ddf808df5651fb2747a46a17cecf8ed5fd1af2
  preresolved: true
