apiVersion: kbld.k14s.io/v1alpha1
kind: Config
overrides:
    - image: quay.io/kiwigrid/k8s-sidecar:1.30.10
      newImage: oci.zebradil.dev/quay.io-cache/kiwigrid/k8s-sidecar:1.30.10
    - image: quay.io/prometheus/node-exporter:v1.10.2
      newImage: oci.zebradil.dev/quay.io-cache/prometheus/node-exporter:v1.10.2
    - image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.17.0
      newImage: oci.zebradil.dev/registry.k8s.io-cache/kube-state-metrics/kube-state-metrics:v2.17.0
