apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.49.0
overrides:
- image: docker.io/grafana/grafana:13.1.1
  newImage: index.docker.io/grafana/grafana@sha256:7cb8c64c4d57a57e734073f3cc94620adb24a0acb929bd80ba9f14017e3a975b
  preresolved: true
- image: docker.io/library/busybox:1.38.0
  newImage: index.docker.io/library/busybox@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
  preresolved: true
- image: quay.io/kiwigrid/k8s-sidecar:2.8.1
  newImage: oci.zebradil.dev/quay.io-cache/kiwigrid/k8s-sidecar@sha256:abb55b2165c60e8f97e473862c7a3123df6f67d44f592949577c29b8fb2df9d6
  preresolved: true
- image: quay.io/prometheus/node-exporter:v1.11.1
  newImage: oci.zebradil.dev/quay.io-cache/prometheus/node-exporter@sha256:0f422f62c15f154af8d8572b23d623aebfb10cec73a5c654d18f911f3f9df241
  preresolved: true
- image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.19.1
  newImage: oci.zebradil.dev/registry.k8s.io-cache/kube-state-metrics/kube-state-metrics@sha256:85108987d044b18a098126732f98602df408888c0f7d456241f5abefb9744bc1
  preresolved: true
- image: registry.k8s.io/kubectl:v1.33.1
  newImage: oci.zebradil.dev/registry.k8s.io-cache/kubectl@sha256:b678a2eb762525ff5064ed6064071fc0728bf0f009a6afbe7f49fbad3ac56dbf
  preresolved: true
- image: victoriametrics/operator:v0.74.0
  newImage: index.docker.io/victoriametrics/operator@sha256:c4fde419a4f03c7c45d7ee554e7039c12c75af161f7f7e1baef1b343015e3df9
  preresolved: true
